# Generated by Django 4.2.6 on 2023-10-11 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app1eventos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="clase",
            field=models.CharField(
                choices=[("admin", "admin"), ("clien", "clien")],
                default=django.utils.timezone.now,
                max_length=5,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usuario",
            name="contraseña",
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
