# Generated by Django 4.2.6 on 2023-10-17 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1eventos", "0002_usuario_clase_usuario_contraseña"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registroevento",
            name="cantidad_asientos",
        ),
    ]
